### ISSUE TITLE
shouldn’t it be set to ZReviewTender?

### ISSUE THREAD

**Issue by bjjwon** [ZhgChgLi/ZReviewTender#12]
![Image](https://github.com/user-attachments/assets/101e5410-098c-45c4-8157-68918f7c1ae7)

Looking at the current image, it seems that the red-marked section is using the Markdown feature, but shouldn’t it be set to ZReviewTender? I’m receiving great help thanks to you. Thank you, and I look forward to your reply.

**Comment by zhgchgli0718** [comment]
Yes, it should be ZReviewTender.

I mistakenly copied the job name from another project of mine.
Thank you for pointing it out! I’ll fix it shortly.

Fortunately, it's just a label used to identify the job and doesn't affect the actual functionality or execution.

**Comment by bjjwon** [comment]
Thank you
I’m curious whether your current code is for local use or for GitHub Actions. Also, I’d like to know if it’s possible to run it on GitLab CI/CD instead.

**Comment by zhgchgli0718** [comment]
Of course, ZReviewTender is a pure Ruby gem package. You can follow the steps below to set up Ruby, install the ZReviewTender gem, execute ZReviewTender commands, and commit the timestamp log file in GitLab CI/CD:
```
  steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2
    - run: gem install ZReviewTender
      shell: bash
    - run: ZReviewTender -r // OR others ZReviewTender Command
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update latest check timestamp log file."
        commit_user_name: "ZReviewTender"
        commit_user_email: "zhgchgli@gmail.com"
        commit_author: ZReviewTender <zhgchgli@gmail.com>
```
